name: .NET Manual

on:  
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.405
    - name: Node Setup
      uses: actions/setup-node@v2
      with:
          node-version: '15.3.0'

    - name: Restore Tools
      run: |
        dotnet tool install --tool-path . nbgv
        dotnet tool install -g git-release

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c RELEASE /p:PublicRelease=true
    - name: Pack--
      run: |
        npm --version
        gitrelease buildnumber -d -i
        dotnet pack -c RELEASE /p:PublicRelease=true
    - name: Check version
      run: ./nbgv get-version
    - name: Push
      run: dotnet nuget push ./nupkg/git-release.*.nupkg --api-key ${{secrets.NUGETTOKEN}} --source https://api.nuget.org/v3/index.json


