name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
        dotnet-version: 3.0.101

    - name: Restore Tools
      run: dotnet tool install --tool-path . nbgv

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c RELEASE
    - name: Pack--
      run: dotnet pack -c RELEASE /p:PublicRelease=true
    - name: Check version
      run: ./nbgv get-version
    - name: Push
      run: dotnet nuget push ./nupkg/git-release.*.nupkg --api-key ${{secrets.NUGETTOKEN}} --source https://api.nuget.org/v3/index.json


