name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101

    - name: Restore Tools
      run: dotnet tool install --tool-path . nbgv

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Pack--
      run: dotnet pack 
    - name: Check version
      run: ./nbgv get-version
    # - name: Push
    #   run: dotnet nuget push ./nupkg/git-release.$(./nbgv get-version -v NuGetPackageVersion).nupkg --api-key {} --source https://api.nuget.org/v3/index.json


