name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack
    - name: Deploy
      run: dotnet nuget push nupkg/release.1.0.0.nupkg --api-key oy2jcycrwwlteg2g4cgqbqgd2n4z6ixuzosppqcuy56uv4 --source https://api.nuget.org/v3/index.json

