name: .NET

on:  
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        clean: true
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Node Setup
      uses: actions/setup-node@v2
      with:
          node-version: '15.3.0'

    - name: Restore Tools
      run: |
        dotnet --version
        dotnet tool install --tool-path . nbgv
        dotnet tool install --tool-path . git-release

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c RELEASE -p:PublicRelease=true
    
    - name: Update version
      run: |
        npm --version
        npm install
        ./gitrelease buildnumber -d -i -c
    
    - name: Pack
      run: |
        dotnet pack -c RELEASE -p:PublicRelease=true

    - name: Check version
      run: ./nbgv get-version
    
    - name: Push
      run: dotnet nuget push ./nupkg/git-release.*.nupkg --api-key ${{secrets.NUGETTOKEN}} --source https://api.nuget.org/v3/index.json


